parameters:
#    tripminute_accueil.example.class: Tripminute\AccueilBundle\Example

services:
#    tripminute_accueil.example:
#        class: %tripminute_accueil.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
